# Generated by Django 5.1.7 on 2025-09-28 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Hotel Cities',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('hotel', 'Hotel'), ('homestay', 'Homestay'), ('resort', 'Resort'), ('capsule', 'Capsule Hotel'), ('lodge', 'Lodge'), ('farm_stay', 'Farm Stay'), ('villa', 'Villa'), ('luxury_tent', 'Luxury Tent'), ('campground', 'Campground'), ('vacation_home', 'Vacation Home'), ('hostel', 'Hostel'), ('guesthouse', 'Guesthouse')], max_length=100)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('bed_preference', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('queen', 'Queen'), ('king', 'King'), ('twin', 'Twin'), ('bunk', 'Bunk')], max_length=50)),
                ('guest_capacity', models.IntegerField()),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('room_facilities', models.JSONField(blank=True, default=list)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('safety_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operating_hours', models.CharField(max_length=100)),
                ('available_for_booking', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('documents_required', models.TextField()),
                ('terms_and_conditions', models.TextField()),
                ('images', models.JSONField(blank=True, default=list)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_provider', models.ForeignKey(limit_choices_to={'user_type': 'service_provider'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelcity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NomadHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomad_type', models.CharField(choices=[('luxury', 'Luxury'), ('budget', 'Budget'), ('mid_range', 'Mid Range'), ('backpacker', 'Backpacker'), ('co_living', 'Co-Living'), ('workation', 'Workation')], max_length=100)),
                ('work_friendly', models.BooleanField(default=False)),
                ('wifi_speed', models.CharField(blank=True, max_length=50, null=True)),
                ('coworking_space', models.BooleanField(default=False)),
                ('community_events', models.BooleanField(default=False)),
                ('additional_info', models.TextField(blank=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Nomad Hotel',
                'verbose_name_plural': 'Nomad Hotels',
            },
        ),
    ]
