# Generated by Django 5.1.7 on 2025-10-02 05:35

import apps.hotels.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BedPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HotelFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel Facilities',
            },
        ),
        migrations.CreateModel(
            name='OutdoorFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Room Facilities',
            },
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='available_for_booking',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='price_per_night',
            new_name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='images',
        ),
        migrations.AddField(
            model_name='hotel',
            name='duration',
            field=models.CharField(choices=[('1week', '1 Week'), ('1month', '1 Month'), ('6months', '6 Months')], default='1week', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='total_bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='room_facilities',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='bed_preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.bedpreference'),
        ),
        migrations.CreateModel(
            name='HotelAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='hotels.hotel')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('hotel', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.hotels.utils.hotel_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='hotels.hotel')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review_text', models.TextField()),
                ('verified_booking', models.BooleanField(default=False)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotels.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('hotel', 'user')},
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='outdoor_features',
            field=models.ManyToManyField(blank=True, to='hotels.outdoorfeature'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.propertytype'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='reservation_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotels.reservationtype'),
        ),
        migrations.DeleteModel(
            name='NomadHotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='hotels.hotelfacility'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='room_facilities',
            field=models.ManyToManyField(blank=True, to='hotels.roomfacility'),
        ),
    ]
