# Generated by Django 5.1.7 on 2025-09-28 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidedTripCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Guided Trip Cities',
            },
        ),
        migrations.CreateModel(
            name='GuidedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('vehicle_type', models.CharField(choices=[('2_wheeler', '2 Wheeler'), ('4_wheeler', '4 Wheeler'), ('bicycle', 'Bicycle'), ('trekking', 'Trekking'), ('mixed', 'Mixed Transport')], max_length=50)),
                ('trip_type', models.CharField(choices=[('open', 'Open Trip'), ('closed', 'Closed Trip'), ('guided', 'Guided Trip'), ('self_guided', 'Self Guided')], max_length=50)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('extreme', 'Extreme')], max_length=50)),
                ('intermediate_stops', models.JSONField(blank=True, default=list)),
                ('duration_days', models.IntegerField()),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_participants', models.IntegerField()),
                ('min_participants', models.IntegerField(default=1)),
                ('current_participants', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('trip_schedule', models.JSONField(blank=True, default=dict)),
                ('fare_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('includes', models.JSONField(blank=True, default=list)),
                ('excludes', models.JSONField(blank=True, default=list)),
                ('guide_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guide_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('guide_experience', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_full', models.BooleanField(default=False)),
                ('registration_deadline', models.DateField()),
                ('requirements', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField()),
                ('images', models.JSONField(blank=True, default=list)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to=settings.AUTH_USER_MODEL)),
                ('from_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_from', to='guided_trips.guidedtripcity')),
                ('to_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_to', to='guided_trips.guidedtripcity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('special_requests', models.TextField(blank=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='guided_trips.guidedtrip')),
            ],
            options={
                'unique_together': {('trip', 'participant')},
            },
        ),
    ]
