# Generated by Django 5.1.7 on 2025-10-02 05:35

import apps.guided_trips.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guided_trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Trip Cities',
            },
        ),
        migrations.CreateModel(
            name='TripDifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='guidedtrip',
            old_name='max_participants',
            new_name='group_capacity',
        ),
        migrations.RemoveField(
            model_name='guidedtrip',
            name='images',
        ),
        migrations.AddField(
            model_name='guidedtrip',
            name='total_trips_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guidedtrip',
            name='vehicle_type',
            field=models.CharField(choices=[('2_wheeler', '2 Wheeler'), ('4_wheeler', '4 Wheeler')], max_length=50),
        ),
        migrations.AddField(
            model_name='guidedtrip',
            name='join_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guided_trips.jointype'),
        ),
        migrations.AddField(
            model_name='guidedtrip',
            name='support_features',
            field=models.ManyToManyField(blank=True, to='guided_trips.supportfeature'),
        ),
        migrations.AlterField(
            model_name='guidedtrip',
            name='from_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_from', to='guided_trips.tripcity'),
        ),
        migrations.AlterField(
            model_name='guidedtrip',
            name='to_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_to', to='guided_trips.tripcity'),
        ),
        migrations.AlterField(
            model_name='guidedtrip',
            name='difficulty_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guided_trips.tripdifficultylevel'),
        ),
        migrations.CreateModel(
            name='TripImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.guided_trips.utils.trip_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_images', to='guided_trips.guidedtrip')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tripcity',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guided_trips.tripregion'),
        ),
        migrations.AddField(
            model_name='guidedtrip',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guided_trips.tripregion'),
        ),
        migrations.AlterField(
            model_name='guidedtrip',
            name='trip_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guided_trips.triptype'),
        ),
        migrations.DeleteModel(
            name='GuidedTripCity',
        ),
    ]
