# Generated by Django 5.2.7 on 2025-12-28 10:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulltours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulltour',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='fulltour',
            name='terms_and_conditions',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
