# Generated by Django 5.1.7 on 2025-09-27 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BikeCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Bike Cities',
            },
        ),
        migrations.CreateModel(
            name='BikeFuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BikeRentalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BikeTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.bikecity')),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('model_year', models.IntegerField()),
                ('engine_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('mileage', models.CharField(blank=True, max_length=50, null=True)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('safety_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operating_hours', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('documents_required', models.TextField()),
                ('terms_and_conditions', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_provider', models.ForeignKey(limit_choices_to={'user_type': 'service_provider'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.bikebrand')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.bikecity')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.bikefueltype')),
                ('rental_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.bikerentaltype')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.biketransmission')),
                ('pickup_locations', models.ManyToManyField(to='bikes.pickuplocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
