# Generated by Django 5.1.7 on 2025-09-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='total_trips',
            field=models.IntegerField(default=0),
        ),
    ]
