# Generated by Django 5.1.7 on 2025-09-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_bike_total_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
