# Generated by Django 5.1.7 on 2025-09-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_bikeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='images',
        ),
    ]
