# Generated by Django 5.1.7 on 2025-09-28 13:57

import apps.bikes.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_remove_bike_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeModelYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.AlterField(
            model_name='bikeimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.bikes.utils.bike_image_upload_path),
        ),
    ]
