# Generated by Django 5.1.7 on 2025-09-28 13:58

from django.db import migrations


def populate_bike_model_years(apps, schema_editor):
    Bike = apps.get_model('bikes', 'Bike')
    BikeModelYear = apps.get_model('bikes', 'BikeModelYear')
    
    # Get unique model years from existing bikes
    unique_years = Bike.objects.values_list('model_year', flat=True).distinct()
    
    # Create BikeModelYear records for each unique year
    for year in unique_years:
        if year:  # Skip null values
            BikeModelYear.objects.get_or_create(year=year)


def reverse_populate_bike_model_years(apps, schema_editor):
    # This migration can be reversed by deleting all BikeModelYear records
    BikeModelYear = apps.get_model('bikes', 'BikeModelYear')
    BikeModelYear.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0006_add_bikemodelyear'),
    ]

    operations = [
        migrations.RunPython(
            populate_bike_model_years,
            reverse_populate_bike_model_years
        ),
    ]
