# Generated by Django 5.1.7 on 2025-09-28 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0007_populate_bikemodelyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='model_year_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bikes.bikemodelyear'),
        ),
    ]
