# Generated by Django 5.1.7 on 2025-09-28 14:03

from django.db import migrations


def link_bikes_to_model_years(apps, schema_editor):
    Bike = apps.get_model('bikes', 'Bike')
    BikeModelYear = apps.get_model('bikes', 'BikeModelYear')
    
    # Link each bike to its corresponding BikeModelYear record
    for bike in Bike.objects.all():
        if bike.model_year:
            try:
                model_year_obj = BikeModelYear.objects.get(year=bike.model_year)
                bike.model_year_fk = model_year_obj
                bike.save()
            except BikeModelYear.DoesNotExist:
                # Create the BikeModelYear if it doesn't exist
                model_year_obj = BikeModelYear.objects.create(year=bike.model_year)
                bike.model_year_fk = model_year_obj
                bike.save()


def reverse_link_bikes_to_model_years(apps, schema_editor):
    # Clear all foreign key relationships
    Bike = apps.get_model('bikes', 'Bike')
    Bike.objects.update(model_year_fk=None)


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0008_add_model_year_fk_field'),
    ]

    operations = [
        migrations.RunPython(
            link_bikes_to_model_years,
            reverse_link_bikes_to_model_years
        ),
    ]
