# Generated by Django 5.1.7 on 2025-09-28 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0009_link_bikes_to_model_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='model_year',
        ),
        migrations.AlterField(
            model_name='bike',
            name='model_year_fk',
            field=models.ForeignKey(default=2000, on_delete=django.db.models.deletion.CASCADE, to='bikes.bikemodelyear'),
            preserve_default=False,
        ),
    ]
