# Generated by Django 5.1.7 on 2025-09-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0010_finalize_model_year_normalization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='model_year_fk',
            new_name='model_year',
        ),
    ]
