# Generated by Django 5.1.7 on 2025-09-28 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilgrimageDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('description', models.TextField()),
                ('significance', models.TextField()),
                ('best_time_to_visit', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PilgrimHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('hotel', 'Hotel'), ('homestay', 'Homestay'), ('resort', 'Resort'), ('lodge', 'Lodge'), ('dharamshala', 'Dharamshala'), ('ashram', 'Ashram'), ('guesthouse', 'Guesthouse')], max_length=100)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('bed_preference', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('queen', 'Queen'), ('king', 'King'), ('dormitory', 'Dormitory')], max_length=50)),
                ('guest_capacity', models.IntegerField()),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('room_facilities', models.JSONField(blank=True, default=list)),
                ('religious_facilities', models.JSONField(blank=True, default=list)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('meals_included', models.BooleanField(default=False)),
                ('meal_type', models.CharField(blank=True, max_length=100)),
                ('distance_to_temple', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('near_destinations', models.ManyToManyField(blank=True, to='pilgrim.pilgrimagedestination')),
                ('service_provider', models.ForeignKey(limit_choices_to={'user_type': 'service_provider'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PilgrimTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('region', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('duration_days', models.IntegerField()),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('extreme', 'Extreme')], max_length=50)),
                ('package_type', models.CharField(choices=[('economy', 'Economy'), ('standard', 'Standard'), ('premium', 'Premium'), ('luxury', 'Luxury')], max_length=50)),
                ('max_participants', models.IntegerField()),
                ('min_participants', models.IntegerField(default=1)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('includes', models.JSONField(blank=True, default=list)),
                ('excludes', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('itinerary', models.JSONField(blank=True, default=dict)),
                ('guide_included', models.BooleanField(default=True)),
                ('guide_languages', models.JSONField(blank=True, default=list)),
                ('requirements', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField()),
                ('features', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinations', models.ManyToManyField(to='pilgrim.pilgrimagedestination')),
                ('service_provider', models.ForeignKey(limit_choices_to={'user_type': 'service_provider'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
