# Generated by Django 5.1.7 on 2025-10-02 05:37

import apps.pilgrim.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilgrimDifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PilgrimFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PilgrimPackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PilgrimRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pilgrimagedestination',
            name='images',
        ),
        migrations.RemoveField(
            model_name='pilgrimhotel',
            name='images',
        ),
        migrations.RemoveField(
            model_name='pilgrimtour',
            name='images',
        ),
        migrations.AddField(
            model_name='pilgrimhotel',
            name='total_bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pilgrimtour',
            name='total_bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='pilgrimtour',
            name='features',
        ),
        migrations.AlterField(
            model_name='pilgrimtour',
            name='difficulty_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilgrim.pilgrimdifficultylevel'),
        ),
        migrations.CreateModel(
            name='PilgrimHotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.pilgrim.utils.pilgrim_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='pilgrim.pilgrimhotel')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='pilgrimtour',
            name='package_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilgrim.pilgrimpackagetype'),
        ),
        migrations.AddField(
            model_name='pilgrimagedestination',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pilgrim.pilgrimregion'),
        ),
        migrations.AddField(
            model_name='pilgrimhotel',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pilgrim.pilgrimregion'),
        ),
        migrations.AlterField(
            model_name='pilgrimtour',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pilgrim.pilgrimregion'),
        ),
        migrations.CreateModel(
            name='PilgrimTourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.pilgrim.utils.pilgrim_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_images', to='pilgrim.pilgrimtour')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pilgrimtour',
            name='features',
            field=models.ManyToManyField(blank=True, to='pilgrim.pilgrimfeature'),
        ),
    ]
