# Generated by Django 5.1.7 on 2025-10-02 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TravelInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('summary', models.TextField(help_text='Brief summary for listing', max_length=500)),
                ('insight_type', models.CharField(choices=[('tip', 'Travel Tip'), ('trend', 'Travel Trend'), ('destination', 'Destination Info'), ('seasonal', 'Seasonal Info'), ('budget', 'Budget Guide'), ('safety', 'Safety Info'), ('culture', 'Cultural Info'), ('food', 'Food Guide'), ('transport', 'Transport Info'), ('accommodation', 'Accommodation Guide')], max_length=50)),
                ('relevant_states', models.JSONField(blank=True, default=list)),
                ('relevant_cities', models.JSONField(blank=True, default=list)),
                ('is_global', models.BooleanField(default=False)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='insights/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights.insightcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsightComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='insights.insightcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='insights.travelinsight')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsightLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_likes', to='insights.travelinsight')),
            ],
            options={
                'unique_together': {('insight', 'user')},
            },
        ),
    ]
