# Generated by Django 5.1.7 on 2025-09-28 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampervanBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CampervanCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Campervan Cities',
            },
        ),
        migrations.CreateModel(
            name='CampervanPickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campervans.campervancity')),
            ],
        ),
        migrations.CreateModel(
            name='Campervan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('model_year', models.IntegerField()),
                ('transmission_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20)),
                ('engine_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('mileage', models.CharField(blank=True, max_length=50, null=True)),
                ('seating_capacity', models.IntegerField()),
                ('sleeping_capacity', models.IntegerField()),
                ('toilet', models.CharField(choices=[('none', 'No Toilet'), ('portable', 'Portable Toilet'), ('bathroom_tent', 'Bathroom Tent'), ('wc_with_shower', 'WC with Shower'), ('full_bathroom', 'Full Bathroom')], max_length=50)),
                ('shower', models.CharField(choices=[('none', 'No Shower'), ('inside', 'Inside Shower'), ('outside', 'Outside Shower'), ('both', 'Inside & Outside')], max_length=50)),
                ('kitchen', models.BooleanField(default=False)),
                ('refrigerator', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('solar_panel', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('gps', models.BooleanField(default=False)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('safety_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operating_hours', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('documents_required', models.TextField()),
                ('terms_and_conditions', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_provider', models.ForeignKey(limit_choices_to={'user_type': 'service_provider'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campervans.campervanbrand')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campervans.campervancity')),
                ('pickup_locations', models.ManyToManyField(to='campervans.campervanpickuplocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
