# Generated by Django 5.1.7 on 2025-10-02 05:35

import apps.campervans.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campervans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampervanAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Campervan Amenities',
            },
        ),
        migrations.CreateModel(
            name='CampervanFuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CampervanModelYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='CampervanShower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CampervanToilet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CampervanTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='campervan',
            name='air_conditioning',
        ),
        migrations.RemoveField(
            model_name='campervan',
            name='gps',
        ),
        migrations.RemoveField(
            model_name='campervan',
            name='images',
        ),
        migrations.RemoveField(
            model_name='campervan',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='campervan',
            name='refrigerator',
        ),
        migrations.RemoveField(
            model_name='campervan',
            name='solar_panel',
        ),
        migrations.RemoveField(
            model_name='campervan',
            name='transmission_type',
        ),
        migrations.RemoveField(
            model_name='campervan',
            name='wifi',
        ),
        migrations.AddField(
            model_name='campervan',
            name='baggage_capacity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campervan',
            name='duration',
            field=models.CharField(choices=[('1day', '1 Day'), ('2-7days', '2-7 Days'), ('7+days', '7+ Days')], default='1day', max_length=20),
        ),
        migrations.AddField(
            model_name='campervan',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='campervan',
            name='total_trips',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='campervan',
            name='amenities',
        ),
        migrations.AlterField(
            model_name='campervan',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campervans.campervanfueltype'),
        ),
        migrations.CreateModel(
            name='CampervanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.campervans.utils.campervan_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campervan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campervan_images', to='campervans.campervan')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='campervan',
            name='model_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campervans.campervanmodelyear'),
        ),
        migrations.AlterField(
            model_name='campervan',
            name='shower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campervans.campervanshower'),
        ),
        migrations.AlterField(
            model_name='campervan',
            name='toilet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campervans.campervantoilet'),
        ),
        migrations.AddField(
            model_name='campervan',
            name='transmission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campervans.campervantransmission'),
        ),
        migrations.AddField(
            model_name='campervan',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='campervans.campervanamenity'),
        ),
        migrations.CreateModel(
            name='CampervanAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campervan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='campervans.campervan')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('campervan', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CampervanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review_text', models.TextField()),
                ('verified_booking', models.BooleanField(default=False)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campervan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='campervans.campervan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('campervan', 'user')},
            },
        ),
    ]
